// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Gurpreetsinghguller/marketing-and-revenue-statics/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// AnalyticsUseCaseInterface is an autogenerated mock type for the AnalyticsUseCaseInterface type
type AnalyticsUseCaseInterface struct {
	mock.Mock
}

// GetAnalyticsReport provides a mock function with given fields: ctx
func (_m *AnalyticsUseCaseInterface) GetAnalyticsReport(ctx context.Context) (map[string]interface{}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAnalyticsReport")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCampaignStats provides a mock function with given fields: ctx, campaignID
func (_m *AnalyticsUseCaseInterface) GetCampaignStats(ctx context.Context, campaignID string) (*domain.CampaignStats, error) {
	ret := _m.Called(ctx, campaignID)

	if len(ret) == 0 {
		panic("no return value specified for GetCampaignStats")
	}

	var r0 *domain.CampaignStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.CampaignStats, error)); ok {
		return rf(ctx, campaignID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.CampaignStats); ok {
		r0 = rf(ctx, campaignID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CampaignStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, campaignID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDailyReport provides a mock function with given fields: ctx, date
func (_m *AnalyticsUseCaseInterface) GetDailyReport(ctx context.Context, date string) (map[string]interface{}, error) {
	ret := _m.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for GetDailyReport")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]interface{}, error)); ok {
		return rf(ctx, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]interface{}); ok {
		r0 = rf(ctx, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMonthlyReport provides a mock function with given fields: ctx, month
func (_m *AnalyticsUseCaseInterface) GetMonthlyReport(ctx context.Context, month string) (map[string]interface{}, error) {
	ret := _m.Called(ctx, month)

	if len(ret) == 0 {
		panic("no return value specified for GetMonthlyReport")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]interface{}, error)); ok {
		return rf(ctx, month)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]interface{}); ok {
		r0 = rf(ctx, month)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, month)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPublicStats provides a mock function with given fields: ctx
func (_m *AnalyticsUseCaseInterface) GetPublicStats(ctx context.Context) (map[string]interface{}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicStats")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWeeklyReport provides a mock function with given fields: ctx, weekStart
func (_m *AnalyticsUseCaseInterface) GetWeeklyReport(ctx context.Context, weekStart string) (map[string]interface{}, error) {
	ret := _m.Called(ctx, weekStart)

	if len(ret) == 0 {
		panic("no return value specified for GetWeeklyReport")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]interface{}, error)); ok {
		return rf(ctx, weekStart)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]interface{}); ok {
		r0 = rf(ctx, weekStart)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, weekStart)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAnalyticsUseCaseInterface creates a new instance of AnalyticsUseCaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyticsUseCaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsUseCaseInterface {
	mock := &AnalyticsUseCaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
