// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Gurpreetsinghguller/marketing-and-revenue-statics/internal/domain"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/Gurpreetsinghguller/marketing-and-revenue-statics/internal/rest/auth/usecase"
)

// AuthUseCaseInterface is an autogenerated mock type for the AuthUseCaseInterface type
type AuthUseCaseInterface struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, credentials
func (_m *AuthUseCaseInterface) Login(ctx context.Context, credentials *domain.User) (*usecase.LoginResponse, error) {
	ret := _m.Called(ctx, credentials)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *usecase.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) (*usecase.LoginResponse, error)); ok {
		return rf(ctx, credentials)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) *usecase.LoginResponse); ok {
		r0 = rf(ctx, credentials)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.User) error); ok {
		r1 = rf(ctx, credentials)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, user
func (_m *AuthUseCaseInterface) Register(ctx context.Context, user *domain.User) (*usecase.RegisterResponse, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *usecase.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) (*usecase.RegisterResponse, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) *usecase.RegisterResponse); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthUseCaseInterface creates a new instance of AuthUseCaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthUseCaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthUseCaseInterface {
	mock := &AuthUseCaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
