// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Gurpreetsinghguller/marketing-and-revenue-statics/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// CampaignUseCaseInterface is an autogenerated mock type for the CampaignUseCaseInterface type
type CampaignUseCaseInterface struct {
	mock.Mock
}

// CreateCampaign provides a mock function with given fields: ctx, campaign, userID
func (_m *CampaignUseCaseInterface) CreateCampaign(ctx context.Context, campaign *domain.Campaign, userID string) (*domain.Campaign, error) {
	ret := _m.Called(ctx, campaign, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateCampaign")
	}

	var r0 *domain.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Campaign, string) (*domain.Campaign, error)); ok {
		return rf(ctx, campaign, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Campaign, string) *domain.Campaign); ok {
		r0 = rf(ctx, campaign, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Campaign, string) error); ok {
		r1 = rf(ctx, campaign, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCampaignWithRole provides a mock function with given fields: ctx, campaignID, userID, userRole
func (_m *CampaignUseCaseInterface) DeleteCampaignWithRole(ctx context.Context, campaignID string, userID string, userRole string) error {
	ret := _m.Called(ctx, campaignID, userID, userRole)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCampaignWithRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, campaignID, userID, userRole)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EndCampaign provides a mock function with given fields: ctx, campaignID, userID, userRole
func (_m *CampaignUseCaseInterface) EndCampaign(ctx context.Context, campaignID string, userID string, userRole string) (*domain.Campaign, error) {
	ret := _m.Called(ctx, campaignID, userID, userRole)

	if len(ret) == 0 {
		panic("no return value specified for EndCampaign")
	}

	var r0 *domain.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*domain.Campaign, error)); ok {
		return rf(ctx, campaignID, userID, userRole)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *domain.Campaign); ok {
		r0 = rf(ctx, campaignID, userID, userRole)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, campaignID, userID, userRole)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllCampaigns provides a mock function with given fields: ctx
func (_m *CampaignUseCaseInterface) GetAllCampaigns(ctx context.Context) ([]domain.Campaign, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCampaigns")
	}

	var r0 []domain.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Campaign, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Campaign); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCampaignByID provides a mock function with given fields: ctx, campaignID
func (_m *CampaignUseCaseInterface) GetCampaignByID(ctx context.Context, campaignID string) (*domain.Campaign, error) {
	ret := _m.Called(ctx, campaignID)

	if len(ret) == 0 {
		panic("no return value specified for GetCampaignByID")
	}

	var r0 *domain.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Campaign, error)); ok {
		return rf(ctx, campaignID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Campaign); ok {
		r0 = rf(ctx, campaignID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, campaignID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCampaignsWithFilters provides a mock function with given fields: ctx, userID, userRole, status, budget, isPublic
func (_m *CampaignUseCaseInterface) GetCampaignsWithFilters(ctx context.Context, userID string, userRole string, status string, budget *float64, isPublic *bool) ([]domain.Campaign, error) {
	ret := _m.Called(ctx, userID, userRole, status, budget, isPublic)

	if len(ret) == 0 {
		panic("no return value specified for GetCampaignsWithFilters")
	}

	var r0 []domain.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *float64, *bool) ([]domain.Campaign, error)); ok {
		return rf(ctx, userID, userRole, status, budget, isPublic)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *float64, *bool) []domain.Campaign); ok {
		r0 = rf(ctx, userID, userRole, status, budget, isPublic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *float64, *bool) error); ok {
		r1 = rf(ctx, userID, userRole, status, budget, isPublic)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPublicCampaigns provides a mock function with given fields: ctx
func (_m *CampaignUseCaseInterface) GetPublicCampaigns(ctx context.Context) ([]domain.Campaign, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicCampaigns")
	}

	var r0 []domain.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Campaign, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Campaign); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PatchCampaignStatus provides a mock function with given fields: ctx, campaignID, userID, userRole, status
func (_m *CampaignUseCaseInterface) PatchCampaignStatus(ctx context.Context, campaignID string, userID string, userRole string, status string) (*domain.Campaign, error) {
	ret := _m.Called(ctx, campaignID, userID, userRole, status)

	if len(ret) == 0 {
		panic("no return value specified for PatchCampaignStatus")
	}

	var r0 *domain.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*domain.Campaign, error)); ok {
		return rf(ctx, campaignID, userID, userRole, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *domain.Campaign); ok {
		r0 = rf(ctx, campaignID, userID, userRole, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, campaignID, userID, userRole, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchCampaigns provides a mock function with given fields: ctx, query
func (_m *CampaignUseCaseInterface) SearchCampaigns(ctx context.Context, query string) ([]domain.Campaign, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for SearchCampaigns")
	}

	var r0 []domain.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Campaign, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Campaign); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCampaign provides a mock function with given fields: ctx, campaignID, updatedCampaign, userID, userRole
func (_m *CampaignUseCaseInterface) UpdateCampaign(ctx context.Context, campaignID string, updatedCampaign *domain.Campaign, userID string, userRole string) (*domain.Campaign, error) {
	ret := _m.Called(ctx, campaignID, updatedCampaign, userID, userRole)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCampaign")
	}

	var r0 *domain.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.Campaign, string, string) (*domain.Campaign, error)); ok {
		return rf(ctx, campaignID, updatedCampaign, userID, userRole)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.Campaign, string, string) *domain.Campaign); ok {
		r0 = rf(ctx, campaignID, updatedCampaign, userID, userRole)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *domain.Campaign, string, string) error); ok {
		r1 = rf(ctx, campaignID, updatedCampaign, userID, userRole)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCampaignUseCaseInterface creates a new instance of CampaignUseCaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCampaignUseCaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CampaignUseCaseInterface {
	mock := &CampaignUseCaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
