// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "github.com/Gurpreetsinghguller/marketing-and-revenue-statics/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// CampaignRepo is an autogenerated mock type for the CampaignRepo type
type CampaignRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: campaign
func (_m *CampaignRepo) Create(campaign *domain.Campaign) error {
	ret := _m.Called(campaign)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Campaign) error); ok {
		r0 = rf(campaign)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *CampaignRepo) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *CampaignRepo) GetAll() ([]domain.Campaign, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Campaign, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Campaign); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *CampaignRepo) GetByID(id string) (*domain.Campaign, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Campaign, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Campaign); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPublic provides a mock function with no fields
func (_m *CampaignRepo) GetPublic() ([]domain.Campaign, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPublic")
	}

	var r0 []domain.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Campaign, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Campaign); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWithFilters provides a mock function with given fields: filters
func (_m *CampaignRepo) GetWithFilters(filters map[string]interface{}) ([]domain.Campaign, error) {
	ret := _m.Called(filters)

	if len(ret) == 0 {
		panic("no return value specified for GetWithFilters")
	}

	var r0 []domain.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}) ([]domain.Campaign, error)); ok {
		return rf(filters)
	}
	if rf, ok := ret.Get(0).(func(map[string]interface{}) []domain.Campaign); ok {
		r0 = rf(filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]interface{}) error); ok {
		r1 = rf(filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: query
func (_m *CampaignRepo) Search(query string) ([]domain.Campaign, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []domain.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.Campaign, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.Campaign); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: campaign
func (_m *CampaignRepo) Update(campaign *domain.Campaign) error {
	ret := _m.Called(campaign)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Campaign) error); ok {
		r0 = rf(campaign)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCampaignRepo creates a new instance of CampaignRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCampaignRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *CampaignRepo {
	mock := &CampaignRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
