// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Gurpreetsinghguller/marketing-and-revenue-statics/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// EngagementUseCaseInterface is an autogenerated mock type for the EngagementUseCaseInterface type
type EngagementUseCaseInterface struct {
	mock.Mock
}

// GetCampaignFunnel provides a mock function with given fields: ctx, campaignID
func (_m *EngagementUseCaseInterface) GetCampaignFunnel(ctx context.Context, campaignID string) (*domain.CampaignFunnel, error) {
	ret := _m.Called(ctx, campaignID)

	if len(ret) == 0 {
		panic("no return value specified for GetCampaignFunnel")
	}

	var r0 *domain.CampaignFunnel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.CampaignFunnel, error)); ok {
		return rf(ctx, campaignID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.CampaignFunnel); ok {
		r0 = rf(ctx, campaignID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CampaignFunnel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, campaignID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserCampaignEngagement provides a mock function with given fields: ctx, userID, campaignID
func (_m *EngagementUseCaseInterface) GetUserCampaignEngagement(ctx context.Context, userID string, campaignID string) (map[string]interface{}, error) {
	ret := _m.Called(ctx, userID, campaignID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserCampaignEngagement")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (map[string]interface{}, error)); ok {
		return rf(ctx, userID, campaignID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) map[string]interface{}); ok {
		r0 = rf(ctx, userID, campaignID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, campaignID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserEngagement provides a mock function with given fields: ctx, userID
func (_m *EngagementUseCaseInterface) GetUserEngagement(ctx context.Context, userID string) (*domain.UserEngagement, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserEngagement")
	}

	var r0 *domain.UserEngagement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserEngagement, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserEngagement); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserEngagement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEngagementUseCaseInterface creates a new instance of EngagementUseCaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEngagementUseCaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *EngagementUseCaseInterface {
	mock := &EngagementUseCaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
