// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Gurpreetsinghguller/marketing-and-revenue-statics/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// EventUseCaseInterface is an autogenerated mock type for the EventUseCaseInterface type
type EventUseCaseInterface struct {
	mock.Mock
}

// GetAggregatedMetrics provides a mock function with given fields: ctx, campaignID
func (_m *EventUseCaseInterface) GetAggregatedMetrics(ctx context.Context, campaignID string) (map[string]interface{}, error) {
	ret := _m.Called(ctx, campaignID)

	if len(ret) == 0 {
		panic("no return value specified for GetAggregatedMetrics")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]interface{}, error)); ok {
		return rf(ctx, campaignID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]interface{}); ok {
		r0 = rf(ctx, campaignID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, campaignID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventByID provides a mock function with given fields: ctx, eventID
func (_m *EventUseCaseInterface) GetEventByID(ctx context.Context, eventID string) (*domain.Event, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetEventByID")
	}

	var r0 *domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Event, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Event); ok {
		r0 = rf(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventsByCampaign provides a mock function with given fields: ctx, campaignID
func (_m *EventUseCaseInterface) GetEventsByCampaign(ctx context.Context, campaignID string) ([]domain.Event, error) {
	ret := _m.Called(ctx, campaignID)

	if len(ret) == 0 {
		panic("no return value specified for GetEventsByCampaign")
	}

	var r0 []domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Event, error)); ok {
		return rf(ctx, campaignID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Event); ok {
		r0 = rf(ctx, campaignID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, campaignID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventsByType provides a mock function with given fields: ctx, eventType
func (_m *EventUseCaseInterface) GetEventsByType(ctx context.Context, eventType domain.EventType) ([]domain.Event, error) {
	ret := _m.Called(ctx, eventType)

	if len(ret) == 0 {
		panic("no return value specified for GetEventsByType")
	}

	var r0 []domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.EventType) ([]domain.Event, error)); ok {
		return rf(ctx, eventType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.EventType) []domain.Event); ok {
		r0 = rf(ctx, eventType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.EventType) error); ok {
		r1 = rf(ctx, eventType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventsByUser provides a mock function with given fields: ctx, userID
func (_m *EventUseCaseInterface) GetEventsByUser(ctx context.Context, userID string) ([]domain.Event, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetEventsByUser")
	}

	var r0 []domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Event, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Event); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TrackEvent provides a mock function with given fields: ctx, event
func (_m *EventUseCaseInterface) TrackEvent(ctx context.Context, event *domain.Event) (*domain.Event, error) {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for TrackEvent")
	}

	var r0 *domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Event) (*domain.Event, error)); ok {
		return rf(ctx, event)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Event) *domain.Event); ok {
		r0 = rf(ctx, event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Event) error); ok {
		r1 = rf(ctx, event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEventUseCaseInterface creates a new instance of EventUseCaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventUseCaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventUseCaseInterface {
	mock := &EventUseCaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
