// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "github.com/Gurpreetsinghguller/marketing-and-revenue-statics/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// EventRepo is an autogenerated mock type for the EventRepo type
type EventRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: event
func (_m *EventRepo) Create(event *domain.Event) error {
	ret := _m.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Event) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *EventRepo) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAggregatedMetrics provides a mock function with given fields: campaignID, startDate, endDate
func (_m *EventRepo) GetAggregatedMetrics(campaignID string, startDate string, endDate string) (map[string]interface{}, error) {
	ret := _m.Called(campaignID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetAggregatedMetrics")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (map[string]interface{}, error)); ok {
		return rf(campaignID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) map[string]interface{}); ok {
		r0 = rf(campaignID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(campaignID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with no fields
func (_m *EventRepo) GetAll() ([]domain.Event, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Event, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByCampaignAndDateRange provides a mock function with given fields: campaignID, startDate, endDate
func (_m *EventRepo) GetByCampaignAndDateRange(campaignID string, startDate string, endDate string) ([]domain.Event, error) {
	ret := _m.Called(campaignID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetByCampaignAndDateRange")
	}

	var r0 []domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) ([]domain.Event, error)); ok {
		return rf(campaignID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) []domain.Event); ok {
		r0 = rf(campaignID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(campaignID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByCampaignID provides a mock function with given fields: campaignID
func (_m *EventRepo) GetByCampaignID(campaignID string) ([]domain.Event, error) {
	ret := _m.Called(campaignID)

	if len(ret) == 0 {
		panic("no return value specified for GetByCampaignID")
	}

	var r0 []domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.Event, error)); ok {
		return rf(campaignID)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.Event); ok {
		r0 = rf(campaignID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(campaignID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByDateRange provides a mock function with given fields: startDate, endDate
func (_m *EventRepo) GetByDateRange(startDate string, endDate string) ([]domain.Event, error) {
	ret := _m.Called(startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetByDateRange")
	}

	var r0 []domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]domain.Event, error)); ok {
		return rf(startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(string, string) []domain.Event); ok {
		r0 = rf(startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByEventType provides a mock function with given fields: eventType
func (_m *EventRepo) GetByEventType(eventType domain.EventType) ([]domain.Event, error) {
	ret := _m.Called(eventType)

	if len(ret) == 0 {
		panic("no return value specified for GetByEventType")
	}

	var r0 []domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.EventType) ([]domain.Event, error)); ok {
		return rf(eventType)
	}
	if rf, ok := ret.Get(0).(func(domain.EventType) []domain.Event); ok {
		r0 = rf(eventType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.EventType) error); ok {
		r1 = rf(eventType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByFilter provides a mock function with given fields: filters
func (_m *EventRepo) GetByFilter(filters map[string]interface{}) ([]domain.Event, error) {
	ret := _m.Called(filters)

	if len(ret) == 0 {
		panic("no return value specified for GetByFilter")
	}

	var r0 []domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}) ([]domain.Event, error)); ok {
		return rf(filters)
	}
	if rf, ok := ret.Get(0).(func(map[string]interface{}) []domain.Event); ok {
		r0 = rf(filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]interface{}) error); ok {
		r1 = rf(filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *EventRepo) GetByID(id string) (*domain.Event, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Event, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Event); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserID provides a mock function with given fields: userID
func (_m *EventRepo) GetByUserID(userID string) ([]domain.Event, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.Event, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.Event); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventCountByType provides a mock function with given fields: campaignID, startDate, endDate
func (_m *EventRepo) GetEventCountByType(campaignID string, startDate string, endDate string) (map[domain.EventType]int64, error) {
	ret := _m.Called(campaignID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetEventCountByType")
	}

	var r0 map[domain.EventType]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (map[domain.EventType]int64, error)); ok {
		return rf(campaignID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) map[domain.EventType]int64); ok {
		r0 = rf(campaignID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[domain.EventType]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(campaignID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventsByChannel provides a mock function with given fields: campaignID, startDate, endDate
func (_m *EventRepo) GetEventsByChannel(campaignID string, startDate string, endDate string) (map[string][]domain.Event, error) {
	ret := _m.Called(campaignID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetEventsByChannel")
	}

	var r0 map[string][]domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (map[string][]domain.Event, error)); ok {
		return rf(campaignID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) map[string][]domain.Event); ok {
		r0 = rf(campaignID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(campaignID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalRevenue provides a mock function with given fields: campaignID, startDate, endDate
func (_m *EventRepo) GetTotalRevenue(campaignID string, startDate string, endDate string) (float64, error) {
	ret := _m.Called(campaignID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalRevenue")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (float64, error)); ok {
		return rf(campaignID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) float64); ok {
		r0 = rf(campaignID, startDate, endDate)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(campaignID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEventRepo creates a new instance of EventRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventRepo {
	mock := &EventRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
