// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Gurpreetsinghguller/marketing-and-revenue-statics/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ProfileUseCaseInterface is an autogenerated mock type for the ProfileUseCaseInterface type
type ProfileUseCaseInterface struct {
	mock.Mock
}

// GetProfile provides a mock function with given fields: ctx, userID
func (_m *ProfileUseCaseInterface) GetProfile(ctx context.Context, userID string) (*domain.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProfile provides a mock function with given fields: ctx, userID, updates
func (_m *ProfileUseCaseInterface) UpdateProfile(ctx context.Context, userID string, updates *domain.User) (*domain.User, error) {
	ret := _m.Called(ctx, userID, updates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.User) (*domain.User, error)); ok {
		return rf(ctx, userID, updates)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.User) *domain.User); ok {
		r0 = rf(ctx, userID, updates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *domain.User) error); ok {
		r1 = rf(ctx, userID, updates)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProfileUseCaseInterface creates a new instance of ProfileUseCaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfileUseCaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileUseCaseInterface {
	mock := &ProfileUseCaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
