// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "github.com/Gurpreetsinghguller/marketing-and-revenue-statics/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ReportRepo is an autogenerated mock type for the ReportRepo type
type ReportRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: report
func (_m *ReportRepo) Create(report *domain.Report) error {
	ret := _m.Called(report)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Report) error); ok {
		r0 = rf(report)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *ReportRepo) GetAll() ([]domain.Report, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Report
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Report, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Report); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Report)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByCampaignAndDateRange provides a mock function with given fields: campaignID, startDate, endDate
func (_m *ReportRepo) GetByCampaignAndDateRange(campaignID string, startDate string, endDate string) (*domain.Report, error) {
	ret := _m.Called(campaignID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetByCampaignAndDateRange")
	}

	var r0 *domain.Report
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (*domain.Report, error)); ok {
		return rf(campaignID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) *domain.Report); ok {
		r0 = rf(campaignID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Report)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(campaignID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *ReportRepo) GetByID(id string) (*domain.Report, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Report
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Report, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Report); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Report)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDaily provides a mock function with given fields: campaignID, date
func (_m *ReportRepo) GetDaily(campaignID string, date string) (*domain.Report, error) {
	ret := _m.Called(campaignID, date)

	if len(ret) == 0 {
		panic("no return value specified for GetDaily")
	}

	var r0 *domain.Report
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*domain.Report, error)); ok {
		return rf(campaignID, date)
	}
	if rf, ok := ret.Get(0).(func(string, string) *domain.Report); ok {
		r0 = rf(campaignID, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Report)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(campaignID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMonthly provides a mock function with given fields: campaignID, year, month
func (_m *ReportRepo) GetMonthly(campaignID string, year string, month string) (*domain.Report, error) {
	ret := _m.Called(campaignID, year, month)

	if len(ret) == 0 {
		panic("no return value specified for GetMonthly")
	}

	var r0 *domain.Report
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (*domain.Report, error)); ok {
		return rf(campaignID, year, month)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) *domain.Report); ok {
		r0 = rf(campaignID, year, month)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Report)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(campaignID, year, month)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWeekly provides a mock function with given fields: campaignID, year, week
func (_m *ReportRepo) GetWeekly(campaignID string, year string, week string) (*domain.Report, error) {
	ret := _m.Called(campaignID, year, week)

	if len(ret) == 0 {
		panic("no return value specified for GetWeekly")
	}

	var r0 *domain.Report
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (*domain.Report, error)); ok {
		return rf(campaignID, year, week)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) *domain.Report); ok {
		r0 = rf(campaignID, year, week)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Report)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(campaignID, year, week)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReportRepo creates a new instance of ReportRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportRepo {
	mock := &ReportRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
