server:
  port: "8080"

log:
  level: "info"

auth:
  secret_file: "shared/secret"
  token_ttl: 24h

rate_limit:
  limiter_type: "fixed_window"
  max_requests: 100
  window_seconds: 60

broker:
  type: "mqtt"
  url: "url"
  client_id: "go-app-listener"
  topic: "campaign-events"
